name: Build and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          ( cd ./web-component && npm install && npm run build )
          npm install && npm run build -- --base=/punch-the-keys/
          cp ./dist/assets/index.*.js ./dist/ptk.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
